### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [nttcom/terraform-provider-ecl#18]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by keiichi-hikita** [comment]
Thanks for your comment!
We'll fix this problem in next version. :+1:

**Comment by keiichi-hikita** [comment]
Solved in v1.3.0.
