### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [nttcom/terraform-provider-ecl#27]
I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the develop branch at git commit `0179b9b`

- [ ] The import path of your helper function will have to be changes from `github.com/nttcom/terraform-provider-ecl/` to `github.com/terraform-providers/terraform-provider-ecl/` this is because we move the repository location during the release process of this program. And will allow us to start testing the provider within our TeamCity provider test environment. I will create you an account to view the test output yourself. 
- [x] I was able to get the acceptance tests running but many of the tests are failing due to some environment variables missing. Here’s my [test output](https://github.com/nttcom/terraform-provider-ecl/files/3894769/test.txt), could you provide the addition environment variable because we will beed to get all the tests passing before the first release. 
- [x] The CHANGELOG formatting will have to be updated to conform to the standard provider format since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. You should also include a list of provider objects in this first release. 
- [x] There are a number of mock tests in the provider, what’s the reason for this? 
- [x] What are your thoughts on naming the provider `enterprisecloud` rather then `ecl`? 

- [x] One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. They use it one the AWS provider. you should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] Its required that all the providers dependancies managed using Go Modules and checked into the repo. You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in all 100+ TF providers.  

- [x] Some resources are tagged `v1` and other `v2`, but there are no overlapping names. What’s the reason for this?

- [x] Attributes should be read and set on Read so that differences between the configuration and the actual state can be caught. Any non-scalar values (TypeList, TypeSet, TypeMap) should have errors checked when setting. The reasoning for this is that the provider should never `panic` and should error out instead. 

Let me know if you have any questions.

I looking forward to releasing this provider with you all!

Best,
Chris

**Comment by keiichi-hikita** [comment]
Thank you for your feedback.
We'll create develop branch and would like to add changes into some separate branch.
 
>  I was able to get the acceptance tests running but many of the tests are failing ...

I'll send you environment values by e-mail.

> There are a number of mock tests in the provider, what’s the reason for this?

Some of our resource takes relatively long time to complete.
So we've prepared mock tests to increase efficiency of development.

> What are your thoughts on naming the provider enterprisecloud rather then ecl?

Thanks.
We also thought of using enterprisecloud as name of this provider.

But in other tools relates to Enterprise Cloud uses same name like "eclcli", "eclsdk" ...
So if it is possible, we would like to keep using this "ecl" name.

>  The import path of your helper function will have to be changes from github.com/nttcom/terraform-provider-ecl/ to github.com/terraform-providers/terraform-provider-ecl/ ...

Got it.
We'll start preparing for this change after your acceptance tests finish.

> You should use it along with your development. https://github.com/bflad/tfproviderlint

Great!! I did not know that tool.
We'll get right on it.

>  Its required that all the providers dependancies managed using Go Modules and checked into the repo....

Got it.
We'll store relevant modules into vendor directory.

>  The CHANGELOG formatting will have to be updated to conform to the standard provider format since the changeling ...

Got it.

>  Some resources are tagged v1 and other v2, but there are no overlapping names. What’s the reason for this?

Part of our Enterprise Cloud uses OpenStack as backend cloud engine.
Same as OpenStack provider, each API component has different versions.
This is why we have different versions.

>  Attributes should be read and set on Read so that differences between the configuration and the actual state can be caught. 

Thanks for your advice.
You are saying that we miss storing some parameter at Read method?
We'll check that aspect again!


Anyway, I'll send you the environemnt values soon.
And we will start development to fix above problems.

Best,
Keiichi

**Comment by cgriggs01** [comment]
Hey Team,

A few more items. I was able to get the go ahead on the provider name `ecl`.  The website documentation looks great. Thanks for working on that. 

- [ ] The makefile you have in this repository should be updated to match the standard GNUmakefile across all Terraform providers, feel free to copy the [GitHub provider GNUmakefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=PROVIDER_NAME

- [ ] Could you remove the [build_and_set_provider.sh](https://github.com/nttcom/terraform-provider-ecl/blob/master/scripts/build_and_set_provider.sh)script, it wont be necessary in the new build process. 

- [ ] The acceptance test are starting to run, but I am still hitting an error. Check out the output [here](https://github.com/nttcom/terraform-provider-ecl/files/4173697/test_output.txt)

Let me know if you have any questions. 
Chris

**Comment by cgriggs01** [comment]
Hello Team,

Thanks for the work you've done to build this provider. We're ready to move on to the final phase of the program, which is to create the new repository location and trigger the first build to publish the binary at [releases.hashicorp.com/](https://releases.hashicorp.com/) and website documentation to terraform.io

Can you provide a list of maintainers to be added to the new repository with "write" access for future development? Please send the maintainers emails and GitHub usernames to cgriggs@hashicorp.com. Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

The follow steps and first release will be preformed by me and another HashiCorp engineer. 
- A repository under the same name `terraform-providers-ecl` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- The master will be pushed up to the new repository
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The build and release process will pull from the master branch. 
- The provider binary version will be tagged `1.0.0` per the CHANGELOG.md

Let me know if you have any questions.
